
-- ----------------------------
-- Records of cat_option
-- ----------------------------
INSERT INTO `cat_option` VALUES ('4', 'Cat.I', '继续常规监护', '1', '0');
INSERT INTO `cat_option` VALUES ('5', 'Cat.II', '二十四小时来院评估', '1', '1');
INSERT INTO `cat_option` VALUES ('6', 'Cat.III', '立即来院处理', '1', '2');
INSERT INTO `cat_option` VALUES ('7', 'Cat.I', '继续常规监护', '2', '0');
INSERT INTO `cat_option` VALUES ('8', 'Cat.II', '二十四小时来院评估', '2', '1');
INSERT INTO `cat_option` VALUES ('9', 'Cat.III', '立即来院处理', '2', '2');
INSERT INTO `cat_option` VALUES ('10', 'Cat.I', '继续常规监护', '4', '0');
INSERT INTO `cat_option` VALUES ('11', 'Cat.II', '二十四小时来院评估', '4', '1');
INSERT INTO `cat_option` VALUES ('12', 'Cat.III', '立即来院处理', '4', '2');
INSERT INTO `cat_option` VALUES ('13', 'Cat.I', '继续常规监护', '5', '0');
INSERT INTO `cat_option` VALUES ('14', 'Cat.II', '二十四小时来院评估', '5', '1');
INSERT INTO `cat_option` VALUES ('15', 'Cat.III', '立即来院处理', '5', '2');
INSERT INTO `cat_option` VALUES ('16', 'Cat.I', '继续常规监护', '6', '1');
INSERT INTO `cat_option` VALUES ('17', 'Cat.II', '二十四小时来院评估', '6', '2');
INSERT INTO `cat_option` VALUES ('18', 'Cat.III', '立即来院处理', '6', '3');
INSERT INTO `cat_option` VALUES ('19', 'Cat.I', '继续常规监护', '7', '1');
INSERT INTO `cat_option` VALUES ('20', 'Cat.II', '二十四小时来院评估', '7', '2');
INSERT INTO `cat_option` VALUES ('21', 'Cat.III', '立即来院处理', '7', '3');
INSERT INTO `cat_option` VALUES ('22', 'Cat.I', '继续常规监护', '8', '1');
INSERT INTO `cat_option` VALUES ('23', 'Cat.II', '二十四小时来院评估', '8', '2');
INSERT INTO `cat_option` VALUES ('24', 'Cat.III', '立即来院处理', '8', '3');
INSERT INTO `cat_option` VALUES ('28', 'Cat.I', '继续常规监护', '9', '0');
INSERT INTO `cat_option` VALUES ('29', 'Cat.II', '二十四小时来院评估', '9', '1');
INSERT INTO `cat_option` VALUES ('30', 'Cat.III', '立即来院处理', '9', '2');
INSERT INTO `cat_option` VALUES ('31', 'Cat.I', '继续常规监护', '10', '0');
INSERT INTO `cat_option` VALUES ('32', 'Cat.II', '二十四小时来院评估', '10', '1');
INSERT INTO `cat_option` VALUES ('33', 'Cat.III', '立即来院处理', '10', '2');
-- ----------------------------
-- Records of nst_option
-- ----------------------------
INSERT INTO `nst_option` VALUES ('5', '正常NST(+)', '继续常规监护，具备条件的每日监护', '1', '0');
INSERT INTO `nst_option` VALUES ('6', '不典型NST(+-)', '二十四小时来院进一步检查评估', '1', '1');
INSERT INTO `nst_option` VALUES ('7', '异常NST(-)', '立即来院，全面评估胎儿状况', '1', '2');
INSERT INTO `nst_option` VALUES ('9', '正常NST(+)', '继续常规监护，具备条件的每日监护', '2', '0');
INSERT INTO `nst_option` VALUES ('10', '不典型NST(+-)', '二十四小时来院进一步检查评估', '2', '1');
INSERT INTO `nst_option` VALUES ('11', '异常NST(-)', '立即来院，全面评估胎儿状况', '2', '2');
INSERT INTO `nst_option` VALUES ('12', ' NST无法判读', ' 继续20分钟监测', '2', '3');
INSERT INTO `nst_option` VALUES ('13', '正常NST(+)', '继续常规监护，具备条件的每日监护', '4', '0');
INSERT INTO `nst_option` VALUES ('14', '不典型NST(+-)', '二十四小时来院进一步检查评估', '4', '1');
INSERT INTO `nst_option` VALUES ('15', '异常NST(-)', '立即来院，全面评估胎儿状况', '4', '2');
INSERT INTO `nst_option` VALUES ('16', ' NST无法判读', ' 继续20分钟监测', '4', '3');
INSERT INTO `nst_option` VALUES ('17', '正常NST(+)', '继续常规监护，具备条件的每日监护', '5', '0');
INSERT INTO `nst_option` VALUES ('18', '不典型NST(+-)', '二十四小时来院进一步检查评估', '5', '1');
INSERT INTO `nst_option` VALUES ('19', '异常NST(-)', '立即来院，全面评估胎儿状况', '5', '2');
INSERT INTO `nst_option` VALUES ('20', ' NST无法判读', ' 继续20分钟监测', '5', '3');
INSERT INTO `nst_option` VALUES ('22', 'NST无法判断：', '继续20分钟监测', '1', '3');
INSERT INTO `nst_option` VALUES ('23', '正常NST(+)', '继续常规监护，具备条件的每日监护', '6', '0');
INSERT INTO `nst_option` VALUES ('24', '不典型NST(+-)', '二十四小时来院进一步检查评估', '6', '2');
INSERT INTO `nst_option` VALUES ('25', '异常NST(-)', '立即来院，全面评估胎儿状况', '6', '3');
INSERT INTO `nst_option` VALUES ('26', ' NST无法判读', ' 继续20分钟监测', '6', '1');
INSERT INTO `nst_option` VALUES ('27', '正常NST(+)', '继续常规监护，具备条件的每日监护', '7', '0');
INSERT INTO `nst_option` VALUES ('28', '不典型NST(+-)', '二十四小时来院进一步检查评估', '7', '2');
INSERT INTO `nst_option` VALUES ('29', '异常NST(-)', '立即来院，全面评估胎儿状况', '7', '3');
INSERT INTO `nst_option` VALUES ('30', ' NST无法判读', ' 继续20分钟监测', '7', '1');
INSERT INTO `nst_option` VALUES ('31', '正常NST(+)', '继续常规监护，具备条件的每日监护', '8', '0');
INSERT INTO `nst_option` VALUES ('32', '不典型NST(+-)', '二十四小时来院进一步检查评估', '8', '2');
INSERT INTO `nst_option` VALUES ('33', '异常NST(-)', '立即来院，全面评估胎儿状况', '8', '3');
INSERT INTO `nst_option` VALUES ('34', ' NST无法判读', ' 继续20分钟监测', '8', '1');
INSERT INTO `nst_option` VALUES ('39', '正常NST(+)', '继续常规监护，具备条件的每日监护', '9', '0');
INSERT INTO `nst_option` VALUES ('40', '不典型NST(+-)', '二十四小时来院进一步检查评估', '9', '1');
INSERT INTO `nst_option` VALUES ('41', '异常NST(-)', '立即来院，全面评估胎儿状况', '9', '2');
INSERT INTO `nst_option` VALUES ('42', ' NST无法判读', ' 继续20分钟监测', '9', '3');
INSERT INTO `nst_option` VALUES ('43', '正常NST(+)', '继续常规监护，具备条件的每日监护', '10', '0');
INSERT INTO `nst_option` VALUES ('44', '不典型NST(+-)', '二十四小时来院进一步检查评估', '10', '1');
INSERT INTO `nst_option` VALUES ('45', '异常NST(-)', '立即来院，全面评估胎儿状况', '10', '2');
INSERT INTO `nst_option` VALUES ('46', ' NST无法判读', ' 继续20分钟监测', '10', '3');

-- ----------------------------
-- Records of report_settings
-- ----------------------------
INSERT INTO `report_settings` VALUES ('1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '3', '6', '5', '1.0', 'default');
INSERT INTO `report_settings` VALUES ('2', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2', '6', '5', '1.0', 'default');
INSERT INTO `report_settings` VALUES ('3', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '6', '5', '1.0', 'default');
INSERT INTO `report_settings` VALUES ('4', '2', '1', '1', '1', '1', '1', '1', null, null, '3', '4', '5', '1.0', 'default');

-- ----------------------------
-- Records of sys_permission
-- ----------------------------
INSERT INTO `sys_permission` VALUES ('100', '首页', '1', 'index', null, 'fa-sliders', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('200', '院内服务', '1', 'insideService', null, 'fa-laptop', '2', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('201', '监护列表', '1', 'insideService.insideServiceList', '/insideService/insideServiceList.do', 'fa-list-ol', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('202', '待监列表', '1', 'insideService.insideServiceListToDeal', '/insideService/insideServiceListToDeal.do', 'fa-list-alt', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('203', '开通院内', '1', 'insideService.insideServiceDeal', '/insideService/insideServiceDeal.do', 'fa-heartbeat', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('300', '外租服务', '1', 'outsideService', null, 'fa-briefcase', '3', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('301', '外租列表', '1', 'outsideService.serviceList', '/service/ServiceList.do', 'fa-bars', '2', '1', '全国外租列表', '0');
INSERT INTO `sys_permission` VALUES ('302', '开通外租', '1', 'outsideService.serviceDeal', '/service/initServiceDeal.do', 'fa-heartbeat', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('303', '服务结算', '2', 'outsideService.serviceList.balance', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('304', '外租列表', '1', 'outsideService.serviceListHospital', '/service/ServiceList.do', 'fa-bars', '1', '1', '院内服务列表', '1');
INSERT INTO `sys_permission` VALUES ('305', '服务结算', '2', 'outsideService.serviceListHospital.balance', null, null, '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('306', '申请退款', '1', 'outsideService.serviceList.refund', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('307', '服务结算', '1', 'outsideService.serviceListHospital.refund', null, null, '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('400', '医生列表', '1', 'doctor', '/staffManage/doctors.do', 'fa-user-md', '5', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('401', '添加医生', '2', 'doctor.add', null, 'fa-plus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('402', '更改信息', '2', 'doctor.update', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('403', '删除医生', '2', 'doctor.delete', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('404', '医生详情', '2', 'doctor.doctorDetail', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('405', '医生列表', '1', 'doctorHospital', '/staffManage/doctors.do', 'fa-user-md', '5', '1', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('406', '添加医生', '2', 'doctorHospital.add', '', 'fa-plus', '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('407', '删除医生', '2', 'doctorHospital.delete', '', 'fa-minus', '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('408', '医生详情', '2', 'doctorHospital.doctorDetail', null, null, '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('409', '医生列表', '1', 'doctorDepartment', '/staffManage/doctors.do', 'fa-user-md', '5', '1', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('410', '添加医生', '2', 'doctorDepartment.add', '', 'fa-plus', '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('411', '删除医生', '2', 'doctorDepartment.delete', '', 'fa-minus', '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('412', '医生详情', '2', 'doctorDepartment.doctorDetail', null, null, '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('413', '更改信息', '2', 'doctorHospital.update', null, null, '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('414', '更改信息', '2', 'doctorDepartment.update', null, null, '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('415', '重置密码', '2', 'doctor.doctorPwdReset', null, null, '1', '0', '医生密码重置', '1');
INSERT INTO `sys_permission` VALUES ('416', '重置密码', '2', 'doctorDepartment.doctorPwdReset', null, null, '1', '0', '医生密码重置', '1');
INSERT INTO `sys_permission` VALUES ('417', '重置密码', '2', 'doctorHospital.doctorPwdReset', null, null, '1', '0', '医生密码重置', '1');
INSERT INTO `sys_permission` VALUES ('500', '孕妇列表', '1', 'gravida', '/staffManage/users.do', 'fa-female', '6', '1', '此为各院孕妇总列表', '0');
INSERT INTO `sys_permission` VALUES ('501', '添加孕妇', '2', 'gravida.add', null, 'fa-plus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('502', '更新孕妇信息', '2', 'gravida.update', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('503', '删除孕妇', '2', 'gravida.delete', null, 'fa-minus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('504', '孕妇详情', '1', 'gravida.gravidaDetail', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('505', '孕妇列表', '1', 'gravidaHospital', '/staffManage/users.do', 'fa-female', '6', '1', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('506', '孕妇详情', '2', 'gravidaHospital.gravidaDetail', null, null, '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('507', '添加孕妇', '2', 'gravidaHospital.add', null, null, '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('508', '修改孕妇', '2', 'gravidaHospital.update', null, null, '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('509', '删除孕妇', '2', 'gravidaHospital.delete', null, null, '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('510', '重置密码', '2', 'gravida.gravidaPwdReset', null, null, '1', '0', '孕妇密码重置', '1');
INSERT INTO `sys_permission` VALUES ('511', '重置密码', '2', 'gravidaHospital.gravidaPwdReset', null, null, '1', '0', '孕妇密码重置', '1');
INSERT INTO `sys_permission` VALUES ('600', '管理员列表', '1', 'customer', '/staffManage/customers.do', 'fa-user-md', '7', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('601', '添加管理员', '2', 'customer.add', '', 'fa-plus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('602', '更新管理员信息', '2', 'customer.update', '', 'fa-wrench', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('603', '删除管理员', '2', 'customer.delete', '', 'fa-minus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('604', '管理员列表', '1', 'customerHospital', '/staffManage/customers.do', 'fa-user-md', '7', '1', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('605', '添加管理员', '2', 'customerHospital.add', '', 'fa-plus', '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('606', '删除管理员', '2', 'customerHospital.delete', '', 'fa-minus', '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('607', '管理员列表', '1', 'customerDepartment', '/staffManage/customers.do', 'fa-user-md', '7', '1', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('608', '添加客服', '2', 'customerDepartment.add', '', 'fa-plus', '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('609', '删除管理员', '2', 'customerDepartment.delete', '', 'fa-minus', '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('610', '重置密码', '2', 'customer.customerPwdReset', null, null, '1', '0', '医生密码重置', '1');
INSERT INTO `sys_permission` VALUES ('611', '重置密码', '2', 'customerHospital.customerPwdReset', null, null, '1', '0', '医生密码重置', '1');
INSERT INTO `sys_permission` VALUES ('612', '重置密码', '2', 'customerDepartment.customerPwdReset', null, null, '1', '0', '医生密码重置', '1');
INSERT INTO `sys_permission` VALUES ('613', '更新管理员信息', '2', 'customerHospital.update', '', 'fa-wrench', '1', '0', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('614', '更新管理员信息', '2', 'customerDepartment.update', '', 'fa-wrench', '1', '0', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('700', '设备管理', '1', 'devmanage', '', 'fa-building', '8', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('701', '院内设备列表', '1', 'devmanage.devlist', '/fetalheart/devList.do', 'fa-bars', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('702', '添加设备', '1', 'devmanage.devlist.add', '', 'fa-plus', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('703', '更新设备信息', '2', 'devmanage.devlist.update', null, null, '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('704', '删除设备信息', '2', 'devmanage.devOutsidelist.delete', null, 'fa-minus', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('705', '设备总库列表', '1', 'devmanage.devAdminList', '/fetalheart/devAdminList.do', 'fa-list-ol', '1', '1', '此为各院设备总库', '0');
INSERT INTO `sys_permission` VALUES ('706', '添加总库设备', '1', 'devmanage.devAdminList.add', '', '', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('707', '更新总库设备', '1', 'devmanage.devAdminList.update', '', '', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('708', '外租设备列表', '1', 'devmanage.devOutsidelist', '/fetalheart/devOutsidelist.do', 'fa-bars', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('709', '添加外租设备', '1', 'devmanage.devOutsidelist.add', '', 'fa-plus', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('800', '订单列表', '1', 'orderManage.orderList', '/order/orderList.do', 'fa-list-alt', '8', '1', '此为各院订单总和', '0');
INSERT INTO `sys_permission` VALUES ('801', '订单列表', '1', 'orderManage.orderListHospital', '/order/orderList.do', ' fa-list-alt', '8', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('802', '订单详情', '2', 'orderManage.orderDetail', '', ' fa-list-alt', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('803', '订单支付', '2', 'orderManage.orderPay', '', ' ', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('804', '订单取消', '2', 'orderManage.orderCancel', '', ' ', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('805', '确认发货', '2', 'orderManage.confirmDelivery', '', ' ', '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('806', '用户下单', '1', 'orderManage.singleOrder', '/order/singleOrder.do?mobile=', 'fa-cart-plus', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('807', '订单管理', '1', 'orderManage', null, 'fa-shopping-cart', '9', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('900', '退款管理', '1', 'refundManage', '', 'fa-credit-card', '10', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('901', '退款历史列表', '1', 'refundManage.refundHistoryList', '/refund/refundHistoryList.do', 'fa-list-alt', '1', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('902', '退款申请列表', '1', 'refundManage.refundApplyList', '/refund/refundApplyList.do', 'fa-list-ol', '1', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('903', '审批退款', '1', 'refundManage.refundApplyList.approval', '', '', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1000', '系统管理', '1', 'sysManage', null, 'fa-windows', '11', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1003', '租赁设置', '1', 'sysManage.rentSetting', '/setting/rentSetting.do', 'fa-ambulance', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1004', '报告设置', '1', 'sysManage.reportSetting', '/setting/reportSettingList.do', 'fa-file-pdf-o', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1005', '套餐设置', '1', 'sysManage.packageSetting', '/setting/packageSetting.do', 'fa-cubes', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1006', '监护设置', '1', 'sysManage.serviceSetting', '/setting/serviceSetting.do', 'fa-stethoscope', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1100', '权限管理', '1', 'permission', null, ' fa-sliders', '12', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1101', '用户管理', '1', 'permission.user', '/sys/sysUsers.do', 'fa-user', '1', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('1102', '用户组管理', '1', 'permission.group', '/sys/sysRoles.do', 'fa-users', '1', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('1103', '添加用户组', '2', 'permission.group.add', null, 'fa-plus', '3', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1104', '删除用户组', '2', 'permission.group.delete', null, 'fa-minus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1105', '更新用户组', '2', 'permission.group.update', null, 'fa-wrench', '2', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1106', '权限配置', '2', 'permission.group.permset', null, '', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1107', '配置用户组', '2', 'permission.user.update', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1108', '禁用用户', '2', 'permission.user.delete', null, null, '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1109', '用户管理', '1', 'permission.userHospital', '/hospitalPerm/sysUsers.do', 'fa-user', '1', '1', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1110', '用户组管理', '1', 'permission.groupHospital', '/hospitalPerm/sysRoles.do', 'fa-users', '1', '1', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1111', '添加用户组', '2', 'permission.groupHospital.add', null, 'fa-plus', '3', '0', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1112', '删除用户组', '2', 'permission.groupHospital.delete', null, 'fa-minus', '1', '0', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1113', '更新用户组', '2', 'permission.groupHospital.update', null, 'fa-wrench', '2', '0', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1114', '权限配置', '2', 'permission.groupHospital.permset', null, '', '1', '0', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1115', '配置用户组', '2', 'permission.userHospital.update', null, null, '1', '0', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1116', '禁用用户', '2', 'permission.userHospital.delete', null, null, '1', '0', '医院端权限', '1');
INSERT INTO `sys_permission` VALUES ('1200', '医院管理', '1', 'hosManage', null, 'fa-hospital-o', '13', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1201', '医院管理列表', '1', 'hosManage.hosptialInfoList', '/sysManage/hospitalInfoList.do', 'fa-bars', '1', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('1202', '医院信息', '1', 'hosManage.hosptialInfo', '/sysManage/hospitalInfo.do', 'fa-hospital-o', '1', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1203', '修改基本信息', '2', 'hosManage.hosptialInfoList.update', null, 'fa-wrench', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1204', '添加医院', '2', 'hosManage.hosptialInfoList.add', null, 'fa-plus', '1', '0', null, '0');
INSERT INTO `sys_permission` VALUES ('1300', '判读管理', '1', 'readData', null, 'fa-history', '4', '1', null, '1');
INSERT INTO `sys_permission` VALUES ('1301', '未判读', '1', 'readData.readDataList', '/service/readDataList.do', 'fa-bars', '1', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('1302', '已判读', '1', 'readData.replyList', '/advice/replyDataList.do', 'fa-list', '2', '1', null, '0');
INSERT INTO `sys_permission` VALUES ('1303', '已判读详情', '2', 'readData.replyDetail', null, null, '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('1304', '未判读详情', '2', 'readData.askDetail', null, null, '1', '0', null, '1');
INSERT INTO `sys_permission` VALUES ('1305', '未判读', '1', 'readData.readDataListHospital', '/service/readDataList.do', 'fa-bars', '1', '1', '限于医院内部', '1');
INSERT INTO `sys_permission` VALUES ('1306', '未判读', '1', 'readData.readDataListDepartment', '/service/readDataList.do', 'fa-bars', '1', '1', '限于科室内部', '1');
INSERT INTO `sys_permission` VALUES ('1307', '已判读', '1', 'readData.replyListHospital', '/advice/replyDataList.do', 'fa-list', '2', '1', '限于医院内部', '1');

-- ----------------------------
-- Records of sys_role
-- ----------------------------
INSERT INTO `sys_role` VALUES ('1', 'admin', '0');
INSERT INTO `sys_role` VALUES ('2', '医生组', '1');
INSERT INTO `sys_role` VALUES ('3', '客服组', '1');
INSERT INTO `sys_role` VALUES ('4', '医院管理员', '0');

-- ----------------------------
-- Records of sys_role_permission
-- ----------------------------
INSERT INTO `sys_role_permission` VALUES ('1', '100');
INSERT INTO `sys_role_permission` VALUES ('1', '200');
INSERT INTO `sys_role_permission` VALUES ('1', '201');
INSERT INTO `sys_role_permission` VALUES ('1', '202');
INSERT INTO `sys_role_permission` VALUES ('1', '203');
INSERT INTO `sys_role_permission` VALUES ('1', '300');
INSERT INTO `sys_role_permission` VALUES ('1', '301');
INSERT INTO `sys_role_permission` VALUES ('1', '302');
INSERT INTO `sys_role_permission` VALUES ('1', '303');
INSERT INTO `sys_role_permission` VALUES ('1', '306');
INSERT INTO `sys_role_permission` VALUES ('1', '400');
INSERT INTO `sys_role_permission` VALUES ('1', '401');
INSERT INTO `sys_role_permission` VALUES ('1', '402');
INSERT INTO `sys_role_permission` VALUES ('1', '403');
INSERT INTO `sys_role_permission` VALUES ('1', '404');
INSERT INTO `sys_role_permission` VALUES ('1', '415');
INSERT INTO `sys_role_permission` VALUES ('1', '500');
INSERT INTO `sys_role_permission` VALUES ('1', '501');
INSERT INTO `sys_role_permission` VALUES ('1', '502');
INSERT INTO `sys_role_permission` VALUES ('1', '503');
INSERT INTO `sys_role_permission` VALUES ('1', '504');
INSERT INTO `sys_role_permission` VALUES ('1', '510');
INSERT INTO `sys_role_permission` VALUES ('1', '600');
INSERT INTO `sys_role_permission` VALUES ('1', '601');
INSERT INTO `sys_role_permission` VALUES ('1', '602');
INSERT INTO `sys_role_permission` VALUES ('1', '603');
INSERT INTO `sys_role_permission` VALUES ('1', '610');
INSERT INTO `sys_role_permission` VALUES ('1', '700');
INSERT INTO `sys_role_permission` VALUES ('1', '701');
INSERT INTO `sys_role_permission` VALUES ('1', '702');
INSERT INTO `sys_role_permission` VALUES ('1', '703');
INSERT INTO `sys_role_permission` VALUES ('1', '704');
INSERT INTO `sys_role_permission` VALUES ('1', '705');
INSERT INTO `sys_role_permission` VALUES ('1', '706');
INSERT INTO `sys_role_permission` VALUES ('1', '707');
INSERT INTO `sys_role_permission` VALUES ('1', '708');
INSERT INTO `sys_role_permission` VALUES ('1', '709');
INSERT INTO `sys_role_permission` VALUES ('1', '800');
INSERT INTO `sys_role_permission` VALUES ('1', '802');
INSERT INTO `sys_role_permission` VALUES ('1', '803');
INSERT INTO `sys_role_permission` VALUES ('1', '804');
INSERT INTO `sys_role_permission` VALUES ('1', '805');
INSERT INTO `sys_role_permission` VALUES ('1', '806');
INSERT INTO `sys_role_permission` VALUES ('1', '807');
INSERT INTO `sys_role_permission` VALUES ('1', '900');
INSERT INTO `sys_role_permission` VALUES ('1', '901');
INSERT INTO `sys_role_permission` VALUES ('1', '902');
INSERT INTO `sys_role_permission` VALUES ('1', '903');
INSERT INTO `sys_role_permission` VALUES ('1', '1000');
INSERT INTO `sys_role_permission` VALUES ('1', '1003');
INSERT INTO `sys_role_permission` VALUES ('1', '1004');
INSERT INTO `sys_role_permission` VALUES ('1', '1005');
INSERT INTO `sys_role_permission` VALUES ('1', '1006');
INSERT INTO `sys_role_permission` VALUES ('1', '1100');
INSERT INTO `sys_role_permission` VALUES ('1', '1101');
INSERT INTO `sys_role_permission` VALUES ('1', '1102');
INSERT INTO `sys_role_permission` VALUES ('1', '1103');
INSERT INTO `sys_role_permission` VALUES ('1', '1104');
INSERT INTO `sys_role_permission` VALUES ('1', '1105');
INSERT INTO `sys_role_permission` VALUES ('1', '1106');
INSERT INTO `sys_role_permission` VALUES ('1', '1107');
INSERT INTO `sys_role_permission` VALUES ('1', '1108');
INSERT INTO `sys_role_permission` VALUES ('1', '1200');
INSERT INTO `sys_role_permission` VALUES ('1', '1201');
INSERT INTO `sys_role_permission` VALUES ('1', '1202');
INSERT INTO `sys_role_permission` VALUES ('1', '1203');
INSERT INTO `sys_role_permission` VALUES ('1', '1204');
INSERT INTO `sys_role_permission` VALUES ('1', '1300');
INSERT INTO `sys_role_permission` VALUES ('1', '1301');
INSERT INTO `sys_role_permission` VALUES ('1', '1302');
INSERT INTO `sys_role_permission` VALUES ('1', '1303');
INSERT INTO `sys_role_permission` VALUES ('1', '1304');
INSERT INTO `sys_role_permission` VALUES ('2', '100');
INSERT INTO `sys_role_permission` VALUES ('2', '505');
INSERT INTO `sys_role_permission` VALUES ('2', '506');
INSERT INTO `sys_role_permission` VALUES ('2', '507');
INSERT INTO `sys_role_permission` VALUES ('2', '508');
INSERT INTO `sys_role_permission` VALUES ('2', '509');
INSERT INTO `sys_role_permission` VALUES ('2', '511');
INSERT INTO `sys_role_permission` VALUES ('2', '1300');
INSERT INTO `sys_role_permission` VALUES ('2', '1303');
INSERT INTO `sys_role_permission` VALUES ('2', '1304');
INSERT INTO `sys_role_permission` VALUES ('2', '1305');
INSERT INTO `sys_role_permission` VALUES ('2', '1307');
INSERT INTO `sys_role_permission` VALUES ('3', '100');
INSERT INTO `sys_role_permission` VALUES ('3', '200');
INSERT INTO `sys_role_permission` VALUES ('3', '201');
INSERT INTO `sys_role_permission` VALUES ('3', '202');
INSERT INTO `sys_role_permission` VALUES ('3', '203');
INSERT INTO `sys_role_permission` VALUES ('3', '300');
INSERT INTO `sys_role_permission` VALUES ('3', '302');
INSERT INTO `sys_role_permission` VALUES ('3', '304');
INSERT INTO `sys_role_permission` VALUES ('3', '305');
INSERT INTO `sys_role_permission` VALUES ('3', '405');
INSERT INTO `sys_role_permission` VALUES ('3', '406');
INSERT INTO `sys_role_permission` VALUES ('3', '407');
INSERT INTO `sys_role_permission` VALUES ('3', '408');
INSERT INTO `sys_role_permission` VALUES ('3', '413');
INSERT INTO `sys_role_permission` VALUES ('3', '417');
INSERT INTO `sys_role_permission` VALUES ('3', '505');
INSERT INTO `sys_role_permission` VALUES ('3', '506');
INSERT INTO `sys_role_permission` VALUES ('3', '507');
INSERT INTO `sys_role_permission` VALUES ('3', '508');
INSERT INTO `sys_role_permission` VALUES ('3', '509');
INSERT INTO `sys_role_permission` VALUES ('3', '511');
INSERT INTO `sys_role_permission` VALUES ('3', '604');
INSERT INTO `sys_role_permission` VALUES ('3', '605');
INSERT INTO `sys_role_permission` VALUES ('3', '606');
INSERT INTO `sys_role_permission` VALUES ('3', '611');
INSERT INTO `sys_role_permission` VALUES ('3', '613');
INSERT INTO `sys_role_permission` VALUES ('3', '700');
INSERT INTO `sys_role_permission` VALUES ('3', '701');
INSERT INTO `sys_role_permission` VALUES ('3', '702');
INSERT INTO `sys_role_permission` VALUES ('3', '703');
INSERT INTO `sys_role_permission` VALUES ('3', '704');
INSERT INTO `sys_role_permission` VALUES ('3', '705');
INSERT INTO `sys_role_permission` VALUES ('3', '706');
INSERT INTO `sys_role_permission` VALUES ('3', '707');
INSERT INTO `sys_role_permission` VALUES ('3', '708');
INSERT INTO `sys_role_permission` VALUES ('3', '709');
INSERT INTO `sys_role_permission` VALUES ('3', '801');
INSERT INTO `sys_role_permission` VALUES ('3', '802');
INSERT INTO `sys_role_permission` VALUES ('3', '803');
INSERT INTO `sys_role_permission` VALUES ('3', '804');
INSERT INTO `sys_role_permission` VALUES ('3', '805');
INSERT INTO `sys_role_permission` VALUES ('3', '806');
INSERT INTO `sys_role_permission` VALUES ('3', '807');
INSERT INTO `sys_role_permission` VALUES ('3', '1000');
INSERT INTO `sys_role_permission` VALUES ('3', '1003');
INSERT INTO `sys_role_permission` VALUES ('3', '1004');
INSERT INTO `sys_role_permission` VALUES ('3', '1005');
INSERT INTO `sys_role_permission` VALUES ('3', '1006');
INSERT INTO `sys_role_permission` VALUES ('3', '1300');
INSERT INTO `sys_role_permission` VALUES ('3', '1303');
INSERT INTO `sys_role_permission` VALUES ('3', '1304');
INSERT INTO `sys_role_permission` VALUES ('3', '1306');
INSERT INTO `sys_role_permission` VALUES ('3', '1307');
INSERT INTO `sys_role_permission` VALUES ('4', '100');
INSERT INTO `sys_role_permission` VALUES ('4', '200');
INSERT INTO `sys_role_permission` VALUES ('4', '201');
INSERT INTO `sys_role_permission` VALUES ('4', '202');
INSERT INTO `sys_role_permission` VALUES ('4', '203');
INSERT INTO `sys_role_permission` VALUES ('4', '300');
INSERT INTO `sys_role_permission` VALUES ('4', '302');
INSERT INTO `sys_role_permission` VALUES ('4', '304');
INSERT INTO `sys_role_permission` VALUES ('4', '305');
INSERT INTO `sys_role_permission` VALUES ('4', '307');
INSERT INTO `sys_role_permission` VALUES ('4', '405');
INSERT INTO `sys_role_permission` VALUES ('4', '406');
INSERT INTO `sys_role_permission` VALUES ('4', '407');
INSERT INTO `sys_role_permission` VALUES ('4', '408');
INSERT INTO `sys_role_permission` VALUES ('4', '409');
INSERT INTO `sys_role_permission` VALUES ('4', '410');
INSERT INTO `sys_role_permission` VALUES ('4', '411');
INSERT INTO `sys_role_permission` VALUES ('4', '412');
INSERT INTO `sys_role_permission` VALUES ('4', '413');
INSERT INTO `sys_role_permission` VALUES ('4', '414');
INSERT INTO `sys_role_permission` VALUES ('4', '416');
INSERT INTO `sys_role_permission` VALUES ('4', '417');
INSERT INTO `sys_role_permission` VALUES ('4', '505');
INSERT INTO `sys_role_permission` VALUES ('4', '506');
INSERT INTO `sys_role_permission` VALUES ('4', '507');
INSERT INTO `sys_role_permission` VALUES ('4', '508');
INSERT INTO `sys_role_permission` VALUES ('4', '509');
INSERT INTO `sys_role_permission` VALUES ('4', '511');
INSERT INTO `sys_role_permission` VALUES ('4', '604');
INSERT INTO `sys_role_permission` VALUES ('4', '605');
INSERT INTO `sys_role_permission` VALUES ('4', '606');
INSERT INTO `sys_role_permission` VALUES ('4', '607');
INSERT INTO `sys_role_permission` VALUES ('4', '608');
INSERT INTO `sys_role_permission` VALUES ('4', '609');
INSERT INTO `sys_role_permission` VALUES ('4', '611');
INSERT INTO `sys_role_permission` VALUES ('4', '612');
INSERT INTO `sys_role_permission` VALUES ('4', '613');
INSERT INTO `sys_role_permission` VALUES ('4', '614');
INSERT INTO `sys_role_permission` VALUES ('4', '700');
INSERT INTO `sys_role_permission` VALUES ('4', '701');
INSERT INTO `sys_role_permission` VALUES ('4', '702');
INSERT INTO `sys_role_permission` VALUES ('4', '703');
INSERT INTO `sys_role_permission` VALUES ('4', '704');
INSERT INTO `sys_role_permission` VALUES ('4', '708');
INSERT INTO `sys_role_permission` VALUES ('4', '709');
INSERT INTO `sys_role_permission` VALUES ('4', '801');
INSERT INTO `sys_role_permission` VALUES ('4', '802');
INSERT INTO `sys_role_permission` VALUES ('4', '803');
INSERT INTO `sys_role_permission` VALUES ('4', '804');
INSERT INTO `sys_role_permission` VALUES ('4', '805');
INSERT INTO `sys_role_permission` VALUES ('4', '806');
INSERT INTO `sys_role_permission` VALUES ('4', '807');
INSERT INTO `sys_role_permission` VALUES ('4', '1000');
INSERT INTO `sys_role_permission` VALUES ('4', '1003');
INSERT INTO `sys_role_permission` VALUES ('4', '1004');
INSERT INTO `sys_role_permission` VALUES ('4', '1005');
INSERT INTO `sys_role_permission` VALUES ('4', '1006');
INSERT INTO `sys_role_permission` VALUES ('4', '1100');
INSERT INTO `sys_role_permission` VALUES ('4', '1109');
INSERT INTO `sys_role_permission` VALUES ('4', '1110');
INSERT INTO `sys_role_permission` VALUES ('4', '1111');
INSERT INTO `sys_role_permission` VALUES ('4', '1112');
INSERT INTO `sys_role_permission` VALUES ('4', '1113');
INSERT INTO `sys_role_permission` VALUES ('4', '1114');
INSERT INTO `sys_role_permission` VALUES ('4', '1115');
INSERT INTO `sys_role_permission` VALUES ('4', '1116');
INSERT INTO `sys_role_permission` VALUES ('4', '1200');
INSERT INTO `sys_role_permission` VALUES ('4', '1202');
INSERT INTO `sys_role_permission` VALUES ('4', '1300');
INSERT INTO `sys_role_permission` VALUES ('4', '1303');
INSERT INTO `sys_role_permission` VALUES ('4', '1304');
INSERT INTO `sys_role_permission` VALUES ('4', '1305');
INSERT INTO `sys_role_permission` VALUES ('4', '1306');
INSERT INTO `sys_role_permission` VALUES ('4', '1307');


-- ----------------------------
-- Records of sys_user_role
-- ----------------------------
INSERT INTO `sys_user_role` VALUES ('1', '1');
